[[NativeFileDialog]]
arch = "aarch64"
git-tree-sha1 = "27fe7e7cb79ec03acbc117af5867f5e3bbed6533"
os = "macos"

    [[NativeFileDialog.download]]
    sha256 = "da5a8c21c07b2fd0c688554952fbf980638287ce596b5e86268f0db9b1f66db4"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.aarch64-apple-darwin.tar.gz"
[[NativeFileDialog]]
arch = "aarch64"
git-tree-sha1 = "64379fd574967fb7f362406e600ac9e05f48da5e"
libc = "glibc"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "c3e0fe74b5081382b353f5dfe695b54f7a3360739151068de1c0e2cb3eb9fade"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.aarch64-linux-gnu.tar.gz"
[[NativeFileDialog]]
arch = "aarch64"
git-tree-sha1 = "441a03ef9fe2a9a36843ce82311d87ccdf14e913"
libc = "musl"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "b804b25584db98e9ca08b78b272396ae4128524d88298dcd7646515f1bf33339"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.aarch64-linux-musl.tar.gz"
[[NativeFileDialog]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "37c6f84f5ed9ee9fd04239c82e7348eaf11b6eb9"
libc = "glibc"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "aa73c39431704d06940650c53975e71ecc359a2bb9dd8a1b51428ef50e8c43c2"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.armv7l-linux-gnueabihf.tar.gz"
[[NativeFileDialog]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ff3ae76c8ffeeec470530e55c34d058ca612b7b0"
libc = "musl"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "695a4744e2db1f96c1037ebe4e0636e8ef20950f93bbb57da08ec728d10c2e7e"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.armv7l-linux-musleabihf.tar.gz"
[[NativeFileDialog]]
arch = "i686"
git-tree-sha1 = "6b11e66992dea97bb7cc74764c847cee660050b4"
libc = "glibc"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "ab6e95cde9119ba5ac7d95ba6ea562aacb5579b6e58a347d6796f438c4b491b9"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.i686-linux-gnu.tar.gz"
[[NativeFileDialog]]
arch = "i686"
git-tree-sha1 = "b2fc5293211024e1170e3177e6549e5d7895fad0"
libc = "musl"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "d94ac2672dab2424031817fe54b7a5352de5f53fe51039cbe5d46740bced703a"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.i686-linux-musl.tar.gz"
[[NativeFileDialog]]
arch = "i686"
git-tree-sha1 = "5bf4b8c49c337ac231225e48dc00c1859407cbbe"
os = "windows"

    [[NativeFileDialog.download]]
    sha256 = "10b9ec2619f23decb0e8ed18c024992be6ab03822f7ac3c1481372b9492b6d34"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.i686-w64-mingw32.tar.gz"
[[NativeFileDialog]]
arch = "powerpc64le"
git-tree-sha1 = "4dfce063894641b7247b8bc0370cc66d8085cbf4"
libc = "glibc"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "51626f15eba3d67668b6d21931f16af3cc6c5f84dda4bc9295088217e91ed923"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.powerpc64le-linux-gnu.tar.gz"
[[NativeFileDialog]]
arch = "x86_64"
git-tree-sha1 = "22c18ce093fa64825c64583474fdeda53275147f"
os = "macos"

    [[NativeFileDialog.download]]
    sha256 = "9a87544e84102f01f1bc714f264911d576dedff18091e88db0da604cd2a6d199"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.x86_64-apple-darwin.tar.gz"
[[NativeFileDialog]]
arch = "x86_64"
git-tree-sha1 = "95ad1d3e99e54a81eeae4212200a3731aeb36696"
libc = "glibc"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "e7c5d4d5765caec1c38b3ac495db0cd4de4d2919db9849f74658f4e97e7d5eae"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.x86_64-linux-gnu.tar.gz"
[[NativeFileDialog]]
arch = "x86_64"
git-tree-sha1 = "8e1018c6d89600020d2ce1f1a8d3e38cc3426a70"
libc = "musl"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "ab609573c9ad341b42ccb9513865eb8b2d4ff276fe8e93665700579002dc5b82"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.x86_64-linux-musl.tar.gz"
[[NativeFileDialog]]
arch = "x86_64"
git-tree-sha1 = "d38ad9ae744e8a16c50e9a7cb30ed60892ae5ef5"
os = "freebsd"

    [[NativeFileDialog.download]]
    sha256 = "d9c7f549d3278a805e04be86d47eb11be54ceb824485c73c6df819877cfc7a66"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.x86_64-unknown-freebsd.tar.gz"
[[NativeFileDialog]]
arch = "x86_64"
git-tree-sha1 = "a012dd09dba931c6185556ab40876ec4506bd7db"
os = "windows"

    [[NativeFileDialog.download]]
    sha256 = "577e3003ca6bb138c90c81de617fd11ec2392d36518a763b3a1eb7dd889794a1"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+1/NativeFileDialog.v1.1.6.x86_64-w64-mingw32.tar.gz"
