[[NativeFileDialog]]
arch = "aarch64"
git-tree-sha1 = "7b31e569523d0aae3fa2f9768ddf118ec41d1aed"
os = "macos"

    [[NativeFileDialog.download]]
    sha256 = "78493fbef5db0d384803d419581d647dfe599fceffac471021cedd23e8ac2ae1"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.aarch64-apple-darwin.tar.gz"
[[NativeFileDialog]]
arch = "aarch64"
git-tree-sha1 = "86a419c82928fe9be701db0902e8637804f5faeb"
libc = "glibc"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "cb7729704cd98babc4d4e5d3e0cbc3c9d94c4ef1745b2f53dfcf3f955b045054"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.aarch64-linux-gnu.tar.gz"
[[NativeFileDialog]]
arch = "aarch64"
git-tree-sha1 = "f691be8dd92eb42541a4737bdab0da067e1f077e"
libc = "musl"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "58ca88142d7b2a09ce5f2f029ecb710d65bd76d1c1cf020b954ad1b4d9530487"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.aarch64-linux-musl.tar.gz"
[[NativeFileDialog]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2b80e0533ebcdb19c08037f6440cc07d7e291081"
libc = "glibc"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "f55d6c08aadfaebc9adc591454f230ae7de8741c21c30a649ec6a1de88a9ed8a"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.armv7l-linux-gnueabihf.tar.gz"
[[NativeFileDialog]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "afe6c6b3d7ac87cfce9b1f5bb0a1862c86a6a9f2"
libc = "musl"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "09a0c8ec0cd1192607b75bff93f867275344f1baedc355ae3fa573475c89955e"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.armv7l-linux-musleabihf.tar.gz"
[[NativeFileDialog]]
arch = "i686"
git-tree-sha1 = "a11e9eda5b9ceec266c497292a1167dd86704bd3"
libc = "glibc"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "415bfdc9d1189fcc56f45d6100e3899a0b6b83183d4bb2f1b31b68b4ec030309"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.i686-linux-gnu.tar.gz"
[[NativeFileDialog]]
arch = "i686"
git-tree-sha1 = "be5c3eb3a612117196e3d2ae46f6bd903a100110"
libc = "musl"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "bb2b16d23a3b4542fd00a557661e6e8083f4e5f4d8c29ef468a19d6a7ab35bcb"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.i686-linux-musl.tar.gz"
[[NativeFileDialog]]
arch = "i686"
git-tree-sha1 = "25adcbf620a735faf3522faf8adabec0dea159fc"
os = "windows"

    [[NativeFileDialog.download]]
    sha256 = "60eda3b2b3a78c0b038d321175e30340be5d40943965f688f43904bfc00a2e44"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.i686-w64-mingw32.tar.gz"
[[NativeFileDialog]]
arch = "powerpc64le"
git-tree-sha1 = "ca18a50164f46bcce3964a0b120c4c806cf8a1f8"
libc = "glibc"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "e20ab89f920b6f82b8b8ff87b1f6b6a2b375125b47e2b00e347bb9eb86288b00"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.powerpc64le-linux-gnu.tar.gz"
[[NativeFileDialog]]
arch = "x86_64"
git-tree-sha1 = "4d8bd8a05d47af138a7693ddafa11e86a057789b"
os = "macos"

    [[NativeFileDialog.download]]
    sha256 = "5f0024e2546720ea24396645f88843f17f38b3c9f6780725a33af5f786db5e96"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.x86_64-apple-darwin.tar.gz"
[[NativeFileDialog]]
arch = "x86_64"
git-tree-sha1 = "6cd2fe6c3886077b63d7d7241b1de3eddb631738"
libc = "glibc"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "4a96d286337f55686a3fe6b5e26da30946490a4f18b20fd841b4b9190f375771"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.x86_64-linux-gnu.tar.gz"
[[NativeFileDialog]]
arch = "x86_64"
git-tree-sha1 = "368f9005de61db06d8ba261bc0d15be386204780"
libc = "musl"
os = "linux"

    [[NativeFileDialog.download]]
    sha256 = "74eaf3b59f61d88328a961d6ed829a97a557f46d8cd44cf99599a5377f61ba76"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.x86_64-linux-musl.tar.gz"
[[NativeFileDialog]]
arch = "x86_64"
git-tree-sha1 = "089ef3a60a24725a23cc1c3eeaee35b528543db7"
os = "freebsd"

    [[NativeFileDialog.download]]
    sha256 = "cfb1c675cbffa6536ba37d6078d7e38b8a79408d78383f1048c5728b987690c9"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.x86_64-unknown-freebsd.tar.gz"
[[NativeFileDialog]]
arch = "x86_64"
git-tree-sha1 = "c76ebd005abf3e5d2eabbed7f27def3878d34966"
os = "windows"

    [[NativeFileDialog.download]]
    sha256 = "051af9c6a1b587f6c42e6f4e7ebbc601f4f83ee9046640408dc9d46ce016d9ce"
    url = "https://github.com/JuliaBinaryWrappers/NativeFileDialog_jll.jl/releases/download/NativeFileDialog-v1.1.6+2/NativeFileDialog.v1.1.6.x86_64-w64-mingw32.tar.gz"
