# Autogenerated wrapper script for NativeFileDialog_jll for aarch64-apple-darwin
export libnfd

using GTK3_jll
JLLWrappers.@generate_wrapper_header("NativeFileDialog")
JLLWrappers.@declare_library_product(libnfd, "@rpath/libnfd.dylib")
function __init__()
    JLLWrappers.@generate_init_header(GTK3_jll)
    JLLWrappers.@init_library_product(
        libnfd,
        "lib/libnfd.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
