# Autogenerated wrapper script for NativeFileDialog_jll for i686-w64-mingw32
export libnfd

using GTK3_jll
JLLWrappers.@generate_wrapper_header("NativeFileDialog")
JLLWrappers.@declare_library_product(libnfd, "libnfd.dll")
function __init__()
    JLLWrappers.@generate_init_header(GTK3_jll)
    JLLWrappers.@init_library_product(
        libnfd,
        "bin\\libnfd.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
